package scp.config;

import net.minecraft.block.Block;
import net.minecraft.block.material.Material;
import scp.blocks.SCP310Candle;
import scp.blocks.SCP310Fire;
import scp.blocks.SCPBlock;
import scp.blocks.SCPBlock009;
import scp.blocks.SCPBlock015;
import scp.blocks.SCPBlock019;
import scp.blocks.SCPBlock076;
import scp.blocks.SCPBlock079;
import scp.blocks.SCPBlock143Leaves;
import scp.blocks.SCPBlock143Log;
import scp.blocks.SCPBlock143Planks;
import scp.blocks.SCPBlock143Sapling;
import scp.blocks.SCPBlock151;
import scp.blocks.SCPBlock261;
import scp.blocks.SCPBlock273Pillar;
import scp.blocks.SCPBlock294;
import scp.blocks.SCPBlock409;
import scp.blocks.SCPBlock513;
import scp.blocks.SCPBlock789J;
import scp.blocks.SCPBlock822Immature;
import scp.blocks.SCPBlock822Mature;
import scp.blocks.SCPBlock914;
import scp.blocks.SCPBlockAlarm;
import scp.blocks.SCPBlockBone;
import scp.blocks.SCPBlockChair;
import scp.blocks.SCPBlockCorrodedDoor;
import scp.blocks.SCPBlockCorrodedIron;
import scp.blocks.SCPBlockCustomWater;
import scp.blocks.SCPBlockDesk;
import scp.blocks.SCPBlockDocument;
import scp.blocks.SCPBlockElectricWool;
import scp.blocks.SCPBlockFlesh;
import scp.blocks.SCPBlockGrate;
import scp.blocks.SCPBlockKeycardSlot;
import scp.blocks.SCPBlockKeycardSlotLv2;
import scp.blocks.SCPBlockKeycardSlotLv3;
import scp.blocks.SCPBlockKeycardSlotOmni;
import scp.blocks.SCPBlockMachine;
import scp.blocks.SCPBlockPoster;
import scp.blocks.SCPBlockRemoteDoorComputer;
import scp.blocks.SCPBlockShelf;
import scp.blocks.SCPBlockSlideDoor;
import scp.blocks.SCPBlockSpawner;
import scp.blocks.SCPBlockToilet;
import scp.blocks.SCPBloodBlock;
import scp.blocks.SCPLockerBlock;
import scp.blocks.SCPPosters;
import scp.blocks.SCPSmokeBlock;

public class SCPBlocks
{
	public static Block blockBloodBlock, blockLocker, blockSCP914, blockDocumentTable, blockMachinery, blockSCP019;
	public static Block blockSCP294;
	public static Block blockSCP261;
	public static Block blockSCP354Still;
	public static Block blockSCP354Flowing;
	public static Block blockKeycardSlotLv1;
	public static Block blockKeycardSlotLv2;
	public static Block blockKeycardSlotLv3;
	public static Block blockKeycardSlotOmni;
	public static Block blockSmokeBlock;
	public static Block blockCorrodedIron;
	public static Block blockSCPspawner;
	public static Block blockGranite;
	public static Block blockSCP310;
	public static Block blockSCP409;
	public static Block blockSCP310Fire;
	public static Block blockElectricWool;
	public static Block blockSCP143Leaves;
	public static Block blockSCP143Log;
	public static Block blockSCP143Sapling;
	public static Block blockSCP143Planks;
	public static Block blockCorrodedDoor;
	public static Block blockSCP006Still;
	public static Block blockSCP006Flowing;
	public static Block blockSCP789J;
	public static Block blockSCP015;
	public static Block blockSlidingDoor;
	public static Block blockGrateBlock;
	public static Block blockSCP079;
	public static Block blockSCP076;
	public static Block blockShelf;
	public static Block blockPoster;
	public static Block blockPoster106;
	public static Block blockPoster173;
	public static Block blockPoster079;
	public static Block blockPoster914;
	public static Block blockSCP151;
	public static Block blockPoster372;
	public static Block blockRemoteDoorComputer;
	public static Block blockSCP273;
	public static Block blockFlesh;
	public static Block blockBone;
	public static Block blockSCP822;
	public static Block blockSCP822Grown;
	public static Block blockSCP009;
	public static Block blockJungleShelf;
	public static Block blockBirchShelf;
	public static Block blockToilet;
	public static Block blockAlarm;
	public static Block blockstoneDesk;
	public static Block blockwoodDesk;
	public static Block blockgraniteDesk;
	public static Block blockmarbleDesk;
	public static Block blockMarble;
	public static Block blockmarbleChair;
	public static Block blockwoodenChair;
	public static Block blockstoneChair;
	public static Block blockSCP513;
	public static Block blockOakShelf;
	public static Block blockSpruceShelf;
	public SCPBlocks()
	{
		super();
	}

	public static void init()
	{
		initBlocks();
	}
	
	public static void initBlocks()
	{
		blockBloodBlock			= new SCPBloodBlock(190).setHardness(1.0F).setUnlocalizedName("Blood Block").setStepSound(Block.soundStoneFootstep).setResistance(2.0F);
		blockLocker				= new SCPLockerBlock(191, 23).setHardness(3.0F).setUnlocalizedName("Reinforced Iron").setStepSound(Block.soundMetalFootstep).setResistance(20.0F);
		blockSCP914				= new SCPBlock914(192).setBlockUnbreakable().setHardness(20.0F).setUnlocalizedName("SCP-914").setStepSound(Block.soundMetalFootstep).setResistance(20.0F);
		blockDocumentTable		= new SCPBlockDocument(193, false).setHardness(2.5F).setResistance(1.0F).setStepSound(Block.soundMetalFootstep).setUnlocalizedName("SCP Document Crafter");
		blockMachinery			= new SCPBlockMachine(194, 21).setHardness(10.0F).setUnlocalizedName("Machine Block").setStepSound(Block.soundMetalFootstep).setResistance(18.0F);
		blockSCP019				= (new SCPBlock019(195, scp.tileentities.SCPTileEntity019.class)).setHardness(100F).setStepSound(Block.soundMetalFootstep).setResistance(100F).setUnlocalizedName("SCP-019");
		blockSCP294				= new SCPBlock294(196).setHardness(2F).setStepSound(Block.soundMetalFootstep).setResistance(100F).setUnlocalizedName("SCP-294");
		blockSCP261				= new SCPBlock261(197).setHardness(10.0F).setStepSound(Block.soundMetalFootstep).setUnlocalizedName("SCP-261").setResistance(20.0F);
		blockSCP354Still		= new SCPBlockCustomWater.SCP354Still(198).setHardness(100F).setLightOpacity(255).setUnlocalizedName("SCP-354 Still");
		blockSCP354Flowing		= new SCPBlockCustomWater.SCP354Flowing(199).setHardness(0F).setLightOpacity(255).setUnlocalizedName("SCP-354 Flowing");
		blockKeycardSlotLv1		= new SCPBlockKeycardSlot(200, 34).setHardness(5F).setResistance(10F).setStepSound(Block.soundMetalFootstep).setUnlocalizedName("Keycard Slot");
		blockKeycardSlotLv2		= new SCPBlockKeycardSlotLv2(201, 34).setHardness(5F).setResistance(10F).setStepSound(Block.soundMetalFootstep).setUnlocalizedName("Keycard Slot Lv2");
		blockKeycardSlotLv3		= new SCPBlockKeycardSlotLv3(202, 34).setHardness(5F).setResistance(10F).setStepSound(Block.soundMetalFootstep).setUnlocalizedName("Keycard Slot Lv3");
		blockKeycardSlotOmni	= new SCPBlockKeycardSlotOmni(203, 34).setHardness(5F).setResistance(10F).setStepSound(Block.soundMetalFootstep).setUnlocalizedName("Omni Keycard Slot");
		blockSmokeBlock			= new SCPSmokeBlock(204, 31).setLightOpacity(255).setLightValue(0F).setHardness(2F).setResistance(20F).setStepSound(Block.soundMetalFootstep).setUnlocalizedName("Smoke Block");
		blockCorrodedIron		= (new SCPBlockCorrodedIron(205, 22)).setHardness(10.0F).setStepSound(Block.soundMetalFootstep).setResistance(100.0F).setUnlocalizedName("Corroded Iron Block");
		blockSCPspawner			= (new SCPBlockSpawner(206, 48)).setHardness(5.0F).setStepSound(soundPDFootstep).setBlockUnbreakable().setResistance(5000.0F).setUnlocalizedName("Pocket Dimension Rock");
		blockGranite			= (new SCPBlock(207, 13, Material.rock).setHardness(3.0F).setResistance(10.0F).setStepSound(Block.soundStoneFootstep).setUnlocalizedName("Granite"));
		blockSCP409				= (new SCPBlock409(208, 5).setHardness(6.0F).setResistance(20.0F).setStepSound(Block.soundGlassFootstep).setUnlocalizedName("SCP-409"));
		blockSCP310				= (new SCP310Candle(209, 37).setHardness(0.0F).setLightValue(0.9375F).setStepSound(Block.soundWoodFootstep).setUnlocalizedName("SCP-310"));
		blockSCP310Fire			= (new SCP310Fire(210).setHardness(0.0F).setLightValue(1.0F).setStepSound(Block.soundWoodFootstep).setUnlocalizedName("SCP-310 Fire"));
		blockElectricWool		= (new SCPBlockElectricWool(211, 64, true).setHardness(3.0F).setStepSound(Block.soundClothFootstep).setResistance(1.0F).setUnlocalizedName("Electric Wool"));
		blockSCP143Leaves		= new SCPBlock143Leaves(212).setHardness(0.2F).setStepSound(Block.soundGrassFootstep).setLightOpacity(1).setUnlocalizedName("SCP-143 leaves");
		blockSCP143Log			= new SCPBlock143Log(213).setHardness(36.0F).setResistance(5F).setStepSound(Block.soundWoodFootstep).setUnlocalizedName("SCP-143 Log");
		blockSCP143Sapling		= (new SCPBlock143Sapling(214, 4)).setHardness(0.1F).setStepSound(Block.soundGrassFootstep).setUnlocalizedName("SCP-143 Sapling");
		blockSCP143Planks		= (new SCPBlock143Planks(215, 2).setHardness(2.0F).setStepSound(Block.soundWoodFootstep).setResistance(1F).setUnlocalizedName("SCP-143 Plank"));
		blockCorrodedDoor		= (new SCPBlockCorrodedDoor(216, Material.iron).setHardness(10.0F).setResistance(100.0F).setStepSound(Block.soundMetalFootstep).setUnlocalizedName("Corroded Iron Door"));
		blockSCP006Still		= new SCPBlockCustomWater.SCP006Still(217).setHardness(100F).setLightOpacity(1).setUnlocalizedName("SCP-006 Still");
		blockSCP006Flowing		= new SCPBlockCustomWater.SCP006Flowing(218).setHardness(100F).setLightOpacity(1).setUnlocalizedName("SCP-006 Flowing");
		blockSCP789J			= (new SCPBlock789J(219, 38).setHardness(2.0F).setStepSound(Block.soundStoneFootstep).setResistance(0.5F).setUnlocalizedName("SCP-789-J"));
		blockSCP015				= (new SCPBlock015(220, 41).setHardness(5.0F).setResistance(10.0F).setStepSound(Block.soundMetalFootstep).setUnlocalizedName("SCP-015"));
		blockSlidingDoor		= (new SCPBlockSlideDoor(221, Material.iron).setHardness(5.0F).setResistance(100.0F).setUnlocalizedName("Sliding Door"));
		blockGrateBlock			= new SCPBlockGrate(222, 42).setHardness(5.0F).setResistance(8F).setStepSound(Block.soundMetalFootstep).setUnlocalizedName("Grate Block");
		blockSCP079				= new SCPBlock079(223, 54).setHardness(5.0F).setResistance(8F).setStepSound(Block.soundMetalFootstep).setUnlocalizedName("SCP-\u00a7k079");
		blockSCP076				= (new SCPBlock076(224, 43, scp.tileentities.SCPTileEntity076.class).setHardness(10.0F).setResistance(10F).setStepSound(Block.soundStoneFootstep).setUnlocalizedName("SCP-076 Spawner"));
		blockShelf				= (new SCPBlockShelf(225, 60, Material.iron).setHardness(2.0F).setStepSound(Block.soundMetalFootstep).setUnlocalizedName("Iron Shelf"));
		//blockStoneCoffin		= (new SCPBlockStoneCoffin(mod_Others.StoneCoffinId, 54).setHardness(2.0F).setStepSound(Block.soundStoneFootstep).setUnlocalizedName("Stone Coffin"));
		blockPoster				= (new SCPBlockPoster(226).setHardness(2.0F).setResistance(5.0F).setStepSound(Block.soundWoodFootstep).setUnlocalizedName("Poster"));
		blockPoster106			= (new SCPPosters(227, 2, 0).setHardness(2.0F).setResistance(5.0F).setStepSound(Block.soundWoodFootstep).setUnlocalizedName("Poster106"));
		blockPoster173			= (new SCPPosters(228, 0, 1).setHardness(2.0F).setResistance(5.0F).setStepSound(Block.soundWoodFootstep).setUnlocalizedName("Poster173"));
		blockPoster079			= (new SCPPosters(229, 4, 2).setHardness(2.0F).setResistance(5.0F).setStepSound(Block.soundWoodFootstep).setUnlocalizedName("Poster079"));
		blockPoster914			= (new SCPPosters(230, 6, 3).setHardness(2.0F).setResistance(5.0F).setStepSound(Block.soundWoodFootstep).setUnlocalizedName("Poster914"));
		blockSCP151				= (new SCPBlock151(231).setHardness(2.0F).setResistance(5.0F).setStepSound(Block.soundWoodFootstep).setUnlocalizedName("SCP-151"));
		blockPoster372			= (new SCPPosters(232, 10, 4).setHardness(2.0F).setResistance(5.0F).setStepSound(Block.soundWoodFootstep).setUnlocalizedName("Poster372"));
		blockRemoteDoorComputer	= (new SCPBlockRemoteDoorComputer(233, 1).setHardness(2.0F).setResistance(3.0F).setStepSound(Block.soundMetalFootstep).setUnlocalizedName("Remote Door Computer"));
		blockSCP273				= (new SCPBlock273Pillar(234, 156).setHardness(1F).setStepSound(Block.soundStoneFootstep).setUnlocalizedName("SCP-273 Pillar"));
		blockFlesh				= (new SCPBlockFlesh(235, 62).setHardness(1F).setStepSound(Block.soundStoneFootstep).setUnlocalizedName("Flesh"));
		blockBone				= (new SCPBlockBone(236, 63).setHardness(3F).setStepSound(Block.soundStoneFootstep).setUnlocalizedName("Bone"));
		blockSCP822				= (new SCPBlock822Immature(237, 67).setHardness(1F).setStepSound(Block.soundClothFootstep).setUnlocalizedName("SCP-822"));
		blockSCP822Grown		= (new SCPBlock822Mature(238, 67).setHardness(1F).setStepSound(Block.soundClothFootstep).setUnlocalizedName("SCP-822"));
		blockSCP009				= (new SCPBlock009(239, 71).setHardness(1.5F).setResistance(0.2F).setStepSound(Block.soundGlassFootstep).setUnlocalizedName("SCP-009"));
		blockToilet				= (new SCPBlockToilet(240, 38).setHardness(2.0F).setStepSound(Block.soundStoneFootstep).setResistance(0.5F).setUnlocalizedName("Toilet"));
		blockAlarm				= (new SCPBlockAlarm(241).setHardness(5.0F).setResistance(20.0F).setStepSound(Block.soundMetalFootstep).setUnlocalizedName("Alarm Block"));
		blockstoneDesk			= (new SCPBlockDesk(242, 1, Material.rock).setHardness(1.5F).setResistance(10.0F).setStepSound(Block.soundStoneFootstep).setUnlocalizedName("Stone Table"));
		blockwoodDesk			= (new SCPBlockDesk(243, 4, Material.wood).setHardness(2.0F).setResistance(5.0F).setStepSound(Block.soundWoodFootstep).setUnlocalizedName("Wooden Table"));
		blockgraniteDesk		= (new SCPBlockDesk(244, 13, Material.rock).setHardness(3.0F).setResistance(10.0F).setStepSound(Block.soundStoneFootstep).setUnlocalizedName("Granite Table"));
		blockmarbleDesk			= (new SCPBlockDesk(245, 38, Material.rock).setHardness(3.0F).setResistance(10.0F).setStepSound(Block.soundStoneFootstep).setUnlocalizedName("Marble Table"));
		blockMarble				= (new SCPBlock(246, 38, Material.rock).setHardness(1.5F).setResistance(5.0F).setStepSound(Block.soundStoneFootstep).setUnlocalizedName("Marble"));
		blockmarbleChair		= (new SCPBlockChair(247, 38, Material.rock).setHardness(3.0F).setResistance(10.0F).setStepSound(Block.soundStoneFootstep).setUnlocalizedName("Marble Chair"));
		blockwoodenChair		= (new SCPBlockChair(248, 4, Material.wood).setHardness(2.0F).setResistance(5.0F).setStepSound(Block.soundWoodFootstep).setUnlocalizedName("Wooden Chair"));
		blockstoneChair			= (new SCPBlockChair(249, 1, Material.rock).setHardness(1.5F).setResistance(10.0F).setStepSound(Block.soundStoneFootstep).setUnlocalizedName("Stone Chair"));
		blockSCP513				= new SCPBlock513(250, 15).setHardness(2.0F).setResistance(2.0F).setStepSound(Block.soundAnvilFootstep).setUnlocalizedName("SCP-513");
		blockOakShelf			= (new SCPBlockShelf(251, 4, Material.wood).setHardness(2.0F).setResistance(5.0F).setStepSound(Block.soundWoodFootstep).setUnlocalizedName("Oak Wood Shelf"));
		blockSpruceShelf		= (new SCPBlockShelf(252, 198, Material.wood).setHardness(2.0F).setResistance(5.0F).setStepSound(Block.soundWoodFootstep).setUnlocalizedName("Spruce Wood Shelf"));
		blockBirchShelf			= (new SCPBlockShelf(253, 214, Material.wood).setHardness(2.0F).setResistance(5.0F).setStepSound(Block.soundWoodFootstep).setUnlocalizedName("Birch Wood Shelf"));
		blockJungleShelf		= (new SCPBlockShelf(254, 199, Material.wood).setHardness(2.0F).setResistance(5.0F).setStepSound(Block.soundWoodFootstep).setUnlocalizedName("Jungle Wood Shelf"));

	}
}
